### ISSUE TITLE
Outdated eth-hash version dependency

### ISSUE THREAD

**Issue by rayrapetyan** [ethereum/eth-bloom#19]
* Version: 1.0.0
* Python:3.6
* OS: osx/linux/win

### What was wrong?
setup.py refers to outdated eth-hash dependency:
"eth-hash>=0.1.0a3,<0.2.0",

Current eth-hash version is 0.2.0

#### Code to reproduce the error

Some projects (e.g. eth-evm (trinity)) will fail to install\run properly:
```sh
# trinity
Traceback (most recent call last):
  File "/ara/venv_python/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/ara/venv_python/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/ara/venv_python/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-hash 0.2.0 (/ara/venv_python/python3/lib/python3.6/site-packages), Requirement.parse('eth-hash<0.2.0,>=0.1.0a3'), {'eth-bloom'})
```

#### How to fix?

Replace appropriate line in setup.py with e.g.:
"eth-hash>=0.1.0a3,<1.0.0",

**Comment by rayrapetyan** [comment]
Jesus, someone already created a Pull-request for that 2 hours ago! Weird... closing ticket.
